######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 24 23:21:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h mainwindow.h
SOURCES += dialog.cpp main.cpp mainwindow.cpp
RESOURCES += dockwidgets.qrc
